version: '3'

services:
  pg:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - 127.0.0.1:6379:6379

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
